[build]
  command = "npm run build"
  publish = ".next"
  functions = "netlify/functions"

[dev]
  command = "next dev -p 3000"
  functions = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"
  STORAGE_POSTGRES_PRISMA_URL = "@STORAGE_POSTGRES_PRISMA_URL"
  STORAGE_POSTGRES_URL_NON_POOLING = "@STORAGE_POSTGRES_URL_NON_POOLING"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  STORAGE_POSTGRES_PRISMA_URL = "@STORAGE_POSTGRES_PRISMA_URL"
  STORAGE_POSTGRES_URL_NON_POOLING = "@STORAGE_POSTGRES_URL_NON_POOLING"
