[build]
  command = "npm run build"
  publish = "out"
  functions = "netlify/functions"

[dev]
  command = "next dev -p 3000"
  functions = "netlify/functions"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"
